export const SITE = {
  name: "Boki Agency",
  brand: "Boki Agency",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.bokiagency.fr",
  email: "contact@bokiagency.fr",
  phone: "",
  // Pas d'adresse physique inventée — utilise areaServed + geo générique Montauban
  city: "Montauban",
  region: "Tarn-et-Garonne",
  department: "82",
  postalCode: "82000",
  country: "FR",
  // Coordonnées centre Montauban (utilisé en JSON-LD geo, pas en adresse postale)
  geo: {
    latitude: 44.0177,
    longitude: 1.3559,
  },
  // Horaires de réponse (signal LocalBusiness pour Google Business Profile)
  openingHours: [
    "Mo-Fr 09:00-18:00",
  ],
  description:
    "Boki Agency crée des sites internet modernes à Montauban et dans le Tarn-et-Garonne : sites vitrines, e-commerce Shopify, click & collect et SEO local pour professionnels.",
  ogImage: "/og-boki-agency.jpg",
  social: {
    instagram: "",
    linkedin: "",
  },
  areaServed: [
    "Montauban",
    "Castelsarrasin",
    "Moissac",
    "Caussade",
    "Montech",
    "Valence d'Agen",
    "Beaumont-de-Lomagne",
    "Saint-Nicolas-de-la-Grave",
    "Verdun-sur-Garonne",
    "Grisolles",
    "Nègrepelisse",
    "Bressols",
    "Labastide-Saint-Pierre",
    "Lafrançaise",
    "Lauzerte",
    "Septfonds",
    "Montbeton",
    "Albias",
    "Saint-Étienne-de-Tulmont",
    "La Ville-Dieu-du-Temple",
    "Auvillar",
    "Lavit",
    "Golfech",
    "Donzac",
    "Toulouse",
    "Agen",
    "Tarn-et-Garonne",
    "82",
  ],
  services: [
    "Création de site internet",
    "Création de site vitrine",
    "Création de site e-commerce",
    "Création de site Shopify",
    "Création de site click & collect",
    "Refonte de site internet",
    "SEO local",
    "Création de vêtements personnalisés",
  ],
} as const;

export const NAV = [
  { href: "/", label: "Accueil" },
  { href: "/services", label: "Services" },
  { href: "/#methode", label: "Méthode" },
  { href: "/a-propos", label: "À propos" },
  { href: "/tarifs-creation-site-internet", label: "Tarifs" },
  { href: "/#faq", label: "FAQ" },
  { href: "/contact", label: "Contact" },
] as const;
